# #########################################################################################
# K8S Service to Billing - Authentication and Authorization microservice (App)
# @author Barbosa, Raphael de Carvalho - raphaelb@cpqd.com.br
# @since 1.0
# #########################################################################################

apiVersion: v1
kind: Service
metadata:
  name: billing-auth-app
spec:
  type: NodePort
  selector:
    app: auth-app
  ports:
  - name: http
    protocol: TCP
    port: 8080
    nodePort: 30000
  - name: debug
    protocol: TCP
    port: 8087
    nodePort: 30087