pipeline {
	agent any

	tools {
		maven "maven-3.6.3"
		jdk "jdk11"
	}

	stages {
		stage('Checkout Source') {
			steps {
				git url:'https://github.com/raphaelcb/new-billing.git', branch:'main'
			}
		}

		stage('Build Source') {
			steps {
				dir("/var/lib/jenkins/workspace/billing-comptech/billing-comptech") {
					sh 'mvn clean install'
				}
			}
		}
	}
}