global:
  scrape_interval: 5s 

scrape_configs:
  - job_name: 'spring-monitoring-app'
    metrics_path: '/tem-cadastro/actuator/prometheus'
    scrape_interval: 5s
    authorization:
      credentials_file: '/home/raphaelb/git/ntem/prometheus/token.txt'
    static_configs:
      - targets: ['192.168.15.85:8080']
