# #########################################################################################
# K8S Deployment to Billing - Authentication and Authorization microservice (Database)
# @author Barbosa, Raphael de Carvalho - raphaelb@cpqd.com.br
# @since 1.0
# #########################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-auth-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-database
  template:
    metadata:
      labels:
        app: auth-database
    spec:
      containers:
      - name: billing-auth-database
        image: raphaelcb/billing-auth-database@sha256:70d9c5e3334fcda479974e3d0eac33129f651cc4dc283dda6140b02663c4b160
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432

---

# #########################################################################################
# K8S Deployment to Billing - Customer microservice (Database)
# @author Barbosa, Raphael de Carvalho - raphaelb@cpqd.com.br
# @since 1.0
# #########################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-customer-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-database
  template:
    metadata:
      labels:
        app: customer-database
    spec:
      containers:
      - name: billing-customer-database
        image: raphaelcb/billing-customer-database@sha256:682e6f22abdbd308a99719124db9c78cf833fe2b7297284107e6a296c38e64fc
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432

--- 

# #########################################################################################
# K8S Deployment to Billing - Authentication and Authorization microservice (App)
# @author Barbosa, Raphael de Carvalho - raphaelb@cpqd.com.br
# @since 1.0
# #########################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
      - name: billing-auth-app
        image: raphaelcb/billing-auth-app@sha256:4bccc333745af3e53edf4cd80c064ec0c64f1bd49207543a4d70a252b65e5ee8
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        env:
          - name: CATALINA_OPTS
            value: "-Xms2048m -Xmx4096m -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true -XX:+UseStringDeduplication 
                    -XX:+OptimizeStringConcat 
                    -XX:+UseG1GC 
                    -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8087"
          - name: JAVA_OPTS
            value: "-DAPP_LOG_ROOT=/opt/billing-auth-app/log 
                    -DAPP_DB_HOME=/opt/billing-auth-app 
                    -Dauth_method=database 
                    -Dauth_attempts=3 
                    -Djwt_issuer=kMRZmzW3qZLXOtdIDrImOpX8LfYzsIF4 
                    -Djwt_issuer_secret=WzicsW1GfyaJoq7puEUc7CBehG2zZgcc 
                    -Djwt_token_expiration=900
                    -Duser.Timezone=GMT-3 
                    -Duser.language=pt 
                    -Duser.country=BR"
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8087
          name: debug

---

# #########################################################################################
# K8S Deployment to Billing - Customer microservice (App)
# @author Barbosa, Raphael de Carvalho - raphaelb@cpqd.com.br
# @since 1.0
# #########################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-customer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-app
  template:
    metadata:
      labels:
        app: customer-app
    spec:
      containers:
      - name: billing-customer-app
        image: raphaelcb/billing-customer-app@sha256:b8147dcb439f23bccff90050f6e73a8b1627a5d2a7e4a81cb2c88ee33c32d3f2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        env:
          - name: CATALINA_OPTS
            value: "-Xms2048m -Xmx4096m -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true -XX:+UseStringDeduplication 
                    -XX:+OptimizeStringConcat 
                    -XX:+UseG1GC 
                    -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8088"
          - name: JAVA_OPTS
            value: "-DAPP_LOG_ROOT=/opt/billing-customer-app/log 
                    -DAPP_DB_HOME=/opt/billing-customer-app 
                    -Dauth_method=database 
                    -Dauth_attempts=3 
                    -Djwt_issuer=kMRZmzW3qZLXOtdIDrImOpX8LfYzsIF4 
                    -Djwt_issuer_secret=WzicsW1GfyaJoq7puEUc7CBehG2zZgcc 
                    -Djwt_token_expiration=900
                    -Duser.Timezone=GMT-3 
                    -Duser.language=pt 
                    -Duser.country=BR"
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8088
          name: debug

---

# #########################################################################################
# K8S Service to Billing - Authentication and Authorization microservice (Database)
# @author Barbosa, Raphael de Carvalho - raphaelb@cpqd.com.br
# @since 1.0
# #########################################################################################

apiVersion: v1
kind: Service
metadata:
  name: billing-auth-database
spec:
  type: NodePort
  selector:
    app: auth-database
  ports:
  - protocol: TCP
    port: 5432
    nodePort: 30033

---

# #########################################################################################
# K8S Service to Billing - Customer microservice (Database)
# @author Barbosa, Raphael de Carvalho - raphaelb@cpqd.com.br
# @since 1.0
# #########################################################################################

apiVersion: v1
kind: Service
metadata:
  name: billing-customer-database
spec:
  type: NodePort
  selector:
    app: customer-database
  ports:
  - protocol: TCP
    port: 5432
    nodePort: 30034

---

# #########################################################################################
# K8S Service to Billing - Authentication and Authorization microservice (App)
# @author Barbosa, Raphael de Carvalho - raphaelb@cpqd.com.br
# @since 1.0
# #########################################################################################

apiVersion: v1
kind: Service
metadata:
  name: billing-auth-app
spec:
  type: NodePort
  selector:
    app: auth-app
  ports:
  - name: http
    protocol: TCP
    port: 8080
    nodePort: 30000
  - name: debug
    protocol: TCP
    port: 8087
    nodePort: 30087

---

# #########################################################################################
# K8S Service to Billing - Customer microservice (App)
# @author Barbosa, Raphael de Carvalho - raphaelb@cpqd.com.br
# @since 1.0
# #########################################################################################

apiVersion: v1
kind: Service
metadata:
  name: billing-customer-app
spec:
  type: NodePort
  selector:
    app: customer-app
  ports:
  - name: http
    protocol: TCP
    port: 8080
    nodePort: 30001
  - name: debug
    protocol: TCP
    port: 8088
    nodePort: 30088