# #########################################################################################
# K8S Deployment to Billing - Authentication and Authorization microservice (Database)
# @author Barbosa, Raphael de Carvalho - raphaelb@cpqd.com.br
# @since 1.0
# #########################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-auth-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-database
  template:
    metadata:
      labels:
        app: auth-database
    spec:
      containers:
      - name: billing-auth-database
        image: raphaelcb/billing-auth-database:{{tag}}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432

---

# #########################################################################################
# K8S Deployment to Billing - Authentication and Authorization microservice (App)
# @author Barbosa, Raphael de Carvalho - raphaelb@cpqd.com.br
# @since 1.0
# #########################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
      - name: billing-auth-app
        image: raphaelcb/billing-auth-app:{{tag}}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        env:
          - name: CATALINA_OPTS
            value: "-Xms2048m -Xmx4096m -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true -XX:+UseStringDeduplication 
                    -XX:+OptimizeStringConcat 
                    -XX:+UseG1GC 
                    -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8087"
          - name: JAVA_OPTS
            value: "-DAPP_LOG_ROOT=/opt/billing-auth-app/log 
                    -DAPP_DB_HOME=/opt/billing-auth-app 
                    -Dauth_method=database 
                    -Dauth_attempts=3 
                    -Djwt_issuer=QQ6p1dtXPbpt8TPBsITDqs8Fmx2xEMIB 
                    -Djwt_issuer_secret=6gqosbCRXfMrSTL4oxBEl4tlS1rIO73Q 
                    -Djwt_token_expiration=900
                    -Duser.Timezone=GMT-3 
                    -Duser.language=pt 
                    -Duser.country=BR"
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8087
          name: debug

---

# #########################################################################################
# K8S Service to Billing - Authentication and Authorization microservice (Database)
# @author Barbosa, Raphael de Carvalho - raphaelb@cpqd.com.br
# @since 1.0
# #########################################################################################

apiVersion: v1
kind: Service
metadata:
  name: billing-auth-database
spec:
  type: NodePort
  selector:
    app: auth-database
  ports:
  - protocol: TCP
    port: 5432
    nodePort: 30033

---

# #########################################################################################
# K8S Service to Billing - Authentication and Authorization microservice (App)
# @author Barbosa, Raphael de Carvalho - raphaelb@cpqd.com.br
# @since 1.0
# #########################################################################################

apiVersion: v1
kind: Service
metadata:
  name: billing-auth-app
spec:
  type: NodePort
  selector:
    app: auth-app
  ports:
  - name: http
    protocol: TCP
    port: 8080
    nodePort: 30000
  - name: debug
    protocol: TCP
    port: 8087
    nodePort: 30087
