apiVersion: v1
kind: Pod
metadata: 
  name: pod-customer-api
spec:
  containers:
    - name: billing-customer-app
      image: raphaelcb/billing-customer-app:1.0
      ports:
        - containerPort: 8080