apiVersion: v1
kind: Pod
metadata:
  name: pod-customer-database
  labels:
    app: customer-database
    version: v1
spec:
  containers:
  - name: billing-customer-database
    image: raphaelcb/billing-customer-database:1.0
    ports:
      - containerPort: 5432

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-customer-app
  labels:
    app: customer-app
    version: v1
spec:
  containers:
  - name: billing-customer-app
    image: raphaelcb/billing-customer-app:1.0
    ports:
      - containerPort: 8080