# #########################################################################################
# K8S Service to Billing - Authentication and Authorization microservice (Database)
# @author Barbosa, Raphael de Carvalho - raphaelb@cpqd.com.br
# @since 1.0
# #########################################################################################

apiVersion: v1
kind: Service
metadata:
  name: billing-auth-database
spec:
  type: NodePort
  selector:
    app: auth-database
  ports:
  - protocol: TCP
    port: 5432
    nodePort: 30033