# #########################################################################################
# K8S Service to Billing - Company microservice (App)
# @author Barbosa, Raphael de Carvalho - raphaelb@cpqd.com.br
# @since 1.0
# #########################################################################################

apiVersion: v1
kind: Service
metadata:
  name: billing-company-app
spec:
  type: NodePort
  selector:
    app: company-app
  ports:
  - name: http
    protocol: TCP
    port: 8080
    nodePort: 30002
  - name: debug
    protocol: TCP
    port: 8089
    nodePort: 30089