# #########################################################################################
# K8S Service to Billing - Company microservice (Database)
# @author Barbosa, Raphael de Carvalho - raphaelb@cpqd.com.br
# @since 1.0
# #########################################################################################

apiVersion: v1
kind: Service
metadata:
  name: billing-company-database
spec:
  type: NodePort
  selector:
    app: company-database
  ports:
  - protocol: TCP
    port: 5432
    nodePort: 30035