# #########################################################################################
# K8S Deployment to Billing - Customer microservice (App)
# @author Barbosa, Raphael de Carvalho - raphaelb@cpqd.com.br
# @since 1.0
# #########################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-customer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-app
  template:
    metadata:
      labels:
        app: customer-app
    spec:
      containers:
      - name: billing-customer-app
        image: raphaelcb/billing-customer-app:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        env:
          - name: CATALINA_OPTS
            value: "-Xms2048m -Xmx4096m -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true -XX:+UseStringDeduplication 
                    -XX:+OptimizeStringConcat 
                    -XX:+UseG1GC 
                    -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8088"
          - name: JAVA_OPTS
            value: "-DAPP_LOG_ROOT=/opt/billing-customer-app/log 
                    -DAPP_DB_HOME=/opt/billing-customer-app 
                    -Dauth_method=database 
                    -Dauth_attempts=3 
                    -Djwt_issuer=QQ6p1dtXPbpt8TPBsITDqs8Fmx2xEMIB 
                    -Djwt_issuer_secret=6gqosbCRXfMrSTL4oxBEl4tlS1rIO73Q 
                    -Djwt_token_expiration=900
                    -Duser.Timezone=GMT-3 
                    -Duser.language=pt 
                    -Duser.country=BR"
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8088
          name: debug