# #########################################################################################
# K8S Service to Billing - Customer microservice (App)
# @author Barbosa, Raphael de Carvalho - raphaelb@cpqd.com.br
# @since 1.0
# #########################################################################################

apiVersion: v1
kind: Service
metadata:
  name: billing-customer-app
spec:
  type: NodePort
  selector:
    app: customer-app
  ports:
  - name: http
    protocol: TCP
    port: 8080
    nodePort: 30001
  - name: debug
    protocol: TCP
    port: 8088
    nodePort: 30088